"""create products table

Revision ID: 8abd5a49b4f0
Revises: 7500ab53684b
Create Date: 2025-12-03 20:41:18.921804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8abd5a49b4f0'
down_revision: Union[str, Sequence[str], None] = '7500ab53684b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'products',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
        sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('quantity', mysql.INTEGER(), nullable=False),
        sa.Column('category_id', mysql.INTEGER(), nullable=False),
        sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
    )
    op.create_index(op.f('name'), 'products', ['name'], unique=True)


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='products')
    op.drop_table('products')
